# Site settings
title: How to Survive EECS 281
author: Waleed Khan
email: wkhan@umich.edu
description: "Tips and tricks for surviving EECS 281 at the University of Michigan."
url: "https://eecs281.waleedkhan.name" # the base hostname & protocol for your site

# We can get a list of categories already, but we want to be sure to display
# them in this order.
all_categories:
  - editing
  - coding
  - workflow

contribute_link: "https://github.com/arxanas/how-to-survive-eecs-281"

# Build settings
markdown: kramdown

google_analytics_id: "UA-53066274-1"
