# Site settings
title: How to Survive EECS 281
author: Waleed Khan
email: wkhan@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Tips and tricks for surviving EECS 281 at the University of Michigan.
baseurl: "/281" # the subpath of your site, e.g. /blog/
url: "http://waleedkhan.name" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

google_analytics_id: "UA-53066274-1"
